In [148]:
# Team 1- social media uses and its impact on mental health of student
# Team 2- academic performance Vs LifeStyle habits of Students




# utilising the modular approach   - jupyter notebook so it is used
# input lib ->  data loading -> eda -> visulization -> model raining -> prediction -> 
# kernel - convert binary file to electrical file to reach at processor to execute and vice vrsa

# arr is not used in pyhton because python stores only obj.
# type of list is object.


# TypeCating - 1. implicit  ( default) low to high
#              2. explicit ( By Force ) high to low




In [16]:
# numpy- numerical python
import numpy as np
# np is a alias of numpy which acts as a obj of numpy
# import statement - 1. Collective     import lib_name
#                    2.Selective       from lib_name import module_name, module_name2

data =[12,54,73,56.7,74]
mean_data = np.mean(data)
print( mean_data)

53.94


In [17]:
print(type(list))

<class 'type'>


In [18]:
arr_data = np.array(data)
# arr_data acts same as a normal array
                    
print(arr_data)
print(arr_data[0])
print(type(arr_data))

[12.  54.  73.  56.7 74. ]
12.0
<class 'numpy.ndarray'>


In [19]:
arr_2d= np.array([[1,2,3],[4,5,6] , [7,8,9]])
print(arr_2d)
print(type(arr_2d))

for i in range(0 , len(arr_2d)):
    for j in range (0 , len(arr_2d[0])):
        print(arr_2d[i][j], end=" ")
    print()


# print() always gives a new line 
# so print("\n") gives two line gap

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
1 2 3 
4 5 6 
7 8 9 


In [20]:
print(np.median(arr_2d))
print(arr_2d[1:2:3])



5.0
[[4 5 6]]


In [21]:
# social media uses and its impact on mental health of student
# academic performance Vs LifeStyle habits of Students
print(arr_2d[:3,:1])

[[1]
 [4]
 [7]]


In [22]:
# integer - i
# float -g
# boolean  - b
# unsigned integer - u
# complex float - c
# string - S
# timedelta - n
# Datetime - m
# Object - O
# void - V


In [23]:
newArr = arr_2d.astype("b")
print(newArr)
print(type(newArr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


<h1>Day 5 </h1>

<h4>Copy as View </h4>

In [24]:
import numpy as np

arr2 = np.array([10, 45, 86, 26])
#copy karne pr  new array me change krne pr original me koi change nhi aaega
x=arr2.copy()
arr2[0]=77
print(x)
print("arr2", arr2)

[10 45 86 26]
arr2 [77 45 86 26]


In [25]:
y = arr2.view() 
#// view me new array me change krne pr original me bhi change hoga
# arr2[0]=89
print(y)
y[1]=50
print("arr2", arr2)

[77 45 86 26]
arr2 [77 50 86 26]


<h3>Array Shape 1</h3>

In [29]:
day5arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(day5arr)
print(day5arr.shape)
print(arr2.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
(4,)


In [30]:
print(day5arr.shape)

(3, 3)


<h4>Reshaping the Array of numpy</h4>

<h5>From 1D to 2D <h5/>

In [33]:
new1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(new1d.shape)

(12,)


In [39]:
reshape_arr = new1d.reshape(3,1,4)  # reshape is used to change the shape of array
print(reshape_arr)
print(reshape_arr.shape)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
(3, 1, 4)


In [44]:
print(day5arr.reshape(9))

[10 20 30 40 50 60 70 80 90]


In [53]:
# unknown2d= new1d.reshape(-1,4)  
# if we not know col or row we give -1 to adjust automatically
unknown2d= new1d.reshape(3,4,-1)
print(unknown2d)
print(unknown2d.shape)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
(3, 4, 1)


In [57]:
print(day5arr.reshape(-1))
# flattening of arr - convert multiDimensional arr into 1dimensional arr  -> reshape(-1) is used

[10 20 30 40 50 60 70 80 90]


<h4> Joining of Array</h4>

In [60]:
arr1= np.array([12,22,32])
arr2= np.array([40,50,60])
arr3= np.array([90,89])
finalarr = np.concatenate((arr1, arr2,arr3))  # used for joining of array
print(finalarr)

[12 22 32 40 50 60 90 89]


In [70]:
ar2d1= np.array([[1,2], [3,4]])
ar2d2= np.array([[5,6],[7,8]])
# newAr2d1= np.concatenate((ar2d1,ar2d2))    # by default axis is 0
newAr2d1= np.concatenate((ar2d1,ar2d2), axis=1)
print(newAr2d1)

[[1 2 5 6]
 [3 4 7 8]]


<h4>Splitting of Array</h4>

In [88]:
splarr = np.array([1,2,3,4,5,6])
newspl =np.split(splarr, 2)
# split always defined arr into equal part
print(newspl)

[array([1, 2, 3]), array([4, 5, 6])]


In [77]:
smartspl = np.array_split(splarr,4)
print(smartspl)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [86]:
splarr1 = np.array( [[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newspl1= np.split(splarr1,2)
print(newspl1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [93]:
smartspl1 = np.array_split(splarr1, 3)
print(smartspl1)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


<h4>Searching in Array</h4>

In [103]:
location = np.where(splarr1 ==4)
# where function returns the list of index of present value
print(location)

(array([1], dtype=int64), array([0], dtype=int64))


In [102]:
# scenerio base search 
scene = np.where(splarr %2 == 1)  # return the list of index of all odd number in splarr
print(scene)

(array([0, 2, 4], dtype=int64),)


<h4>Sorting in Array</h4>

In [105]:
raw = np.array([9,4,7,1,2,8])
print(np.sort(raw))

[1 2 4 7 8 9]


In [140]:
str_data = np.array(["satyam","vishal", "ajay", "ajit"])
print(np.sort(str_data))   # sort the array into lexicographicaly order
print(np.sort(str_data)[::-1]) # sort the array in descending array

['ajay' 'ajit' 'satyam' 'vishal']
['vishal' 'satyam' 'ajit' 'ajay']


In [112]:
raw1 = np.array([[9,4,7,1,2,8],[56,23, 1,1,2,3]])
print(np.sort(raw1))

[[ 1  2  4  7  8  9]
 [ 1  1  2  3 23 56]]


<h1>Generating random Values</h1>

In [120]:
from numpy import random


In [130]:
p = random.rand()*100
# by default random values are between 0 - 1
print(p)

32.71276092525186


In [132]:
q= random.randint(1000, size=(5,5))
print(q)
# randint return only integer value
                  

[[317 726 445 321 802]
 [811  66 254 188 779]
 [833 191 524 864 131]
 [133 383 770  53 667]
 [976 368 880 350 798]]


In [147]:
# random from selected data
choice = random.choice(raw) # it is used to generate random values from a given choice(arr)
print(choice)

4


In [142]:
#random  shuffle a list
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)

[4, 1, 5, 2, 3]


In [146]:
val = random.uniform(12,75)
print(val)

19.716072432353105


In [149]:
# 1. Descriptive Analysis- what has happened  -> 
# 2. Diagnostic Analysis- why it happened     -> visualization
# 3. Predictive Analysis- what will happen    -> algo lago
# 4. Prescriptive Analysis - what should be done -> summary banawo